### PR TITLE
Feat: dao formation

### PR DESCRIPTION
**Pull request by ivelin**
Continued work on DAO Formation based on @0xMakka 's Draft PR #148

### CODE REVIEW

**Comment by lipmaneth** [comment]
screenshot

Our CTA on the new website is "Start Your Company." We should be consistent with our language since we're saying DAO here. Up to this point, we all agreed Company is the right word bc Sporos isn't just for 'DAOs' but we should decide if we want to say "DAO" and then be consistent everywhere. 
<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 107.0.0.0 on Mac OS 10.15.7
Viewport:  1966 x 1177 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-183--sporosdaoapp-dev.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=107.0&resolution=1966x1177&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-183--sporosdaoapp-dev.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6390fc105b7a940009d1bcbb&commentID=6391ef99f275451a6f14ef0c&resolution=resolved)

**Comment by lipmaneth** [comment]
recording

Fields aren't showing on the Name screen.
<details><summary>Browser metadata</summary>





```
Path:      /dao/create/stepper/42161
Browser:   Chrome 107.0.0.0 on Mac OS 10.15.7
Viewport:  1966 x 1177 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-183--sporosdaoapp-dev.netlify.app%2Fdao%2Fcreate%2Fstepper%2F42161&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=107.0&resolution=1966x1177&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-183--sporosdaoapp-dev.netlify.app/dao/create/stepper/42161) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6390fc105b7a940009d1bcbb&commentID=6391f15559c3f91c6c0d5474&resolution=resolved)

**Comment by lipmaneth** [comment]
recording

Can't see info inputted into fields. Also background is gray for founder area where should be white. 
<details><summary>Browser metadata</summary>





```
Path:      /dao/create/stepper/42161
Browser:   Chrome 107.0.0.0 on Mac OS 10.15.7
Viewport:  1966 x 1177 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-183--sporosdaoapp-dev.netlify.app%2Fdao%2Fcreate%2Fstepper%2F42161&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=107.0&resolution=1966x1177&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-183--sporosdaoapp-dev.netlify.app/dao/create/stepper/42161) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6390fc105b7a940009d1bcbb&commentID=6391f3fb0a3ddc1f2ac3a00e&resolution=resolved)

**Comment by lipmaneth** [comment]
recording

I'm able to input a ton of characters in the token symbol field. I believe the max supported by blockchain explorers is 11 but not 100% confident in that.
<details><summary>Browser metadata</summary>





```
Path:      /dao/create/stepper/42161
Browser:   Chrome 107.0.0.0 on Mac OS 10.15.7
Viewport:  1966 x 1177 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-183--sporosdaoapp-dev.netlify.app%2Fdao%2Fcreate%2Fstepper%2F42161&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=107.0&resolution=1966x1177&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-183--sporosdaoapp-dev.netlify.app/dao/create/stepper/42161) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6390fc105b7a940009d1bcbb&commentID=6391f56e55fa37270cde7843&resolution=resolved)

**Comment by kleb-33** [comment]
image
This is what I see when starting the create a LLC flow. Very different colours from lipmans screen. Much of the headings and text on right hand panel are unclear.

**Comment by kleb-33** [comment]
image
Unlike lipmans experience, the company name fields are all showing for me. The panel on the left is clear. Panel on right unclear as in the previous screen.

**Comment by kleb-33** [comment]
image
Founder fields not visible. They do appear when clicked on.

**Comment by kleb-33** [comment]
image
Adding a founder works aside from the visibility.

**Comment by ivelin** [comment]
Good report, Kleb. It shows that the custom theme was not prepared to
handle dark mode. I will go through these inconsistencies and replace them
with default MUI colors and icons.

As we've discussed before, that's one of the many details that need to be
handled when building a custom theme. It's very resource intensive to get
it right in all modes on all devices and all browsers.
It is not an automatic switch from good looking Figma drawings to
production ready code.

**Comment by ivelin** [comment]
OK, good catch. That is another example with custom theming. It's hard to
get it to look good on all devices, modes and browsers. I will go through
these and revert to default MUI options.
The weird thing is that you seem to be using the same OS and browser that I
am testing on and there is still inconsistency in theme color rendering.

**Comment by ivelin** [comment]
Black font on the green button is automatically calculated by MUI in order
to meet usability requirements. Forcing white will break one of the
lighthouse tests for contrast or color blind differences.
It could be many man weeks of effort to try to get a custom theme working
properly. My focus will be on reasonable user experience with MUI defaults
for MMP.
If we want to launch something soon, a pixel perfect match of figma
examples will have to come in a follow up version.

**Comment by ivelin** [comment]
> screenshot
> 
> Our CTA on the new website is "Start Your Company." We should be consistent with our language since we're saying DAO here. Up to this point, we all agreed Company is the right word bc Sporos isn't just for 'DAOs' but we should decide if we want to say "DAO" and then be consistent everywhere.
> 
> Browser metadata
> [Open Deploy Preview](https://deploy-preview-183--sporosdaoapp-dev.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6390fc105b7a940009d1bcbb&commentID=6391ef99f275451a6f14ef0c&resolution=resolved)

OK. Drop here a screenshot of the latest landing page design with the exact language.

**Comment by lipmaneth** [comment]
screenshot

Dark mode has discoloring. @ivelin in Netbee's designs we did not include a dark mode to keep things simple for v1. Idk how complicated it is to create a light mode and dark mode but imo just doing one for v1 is sufficient. 
<details><summary>Browser metadata</summary>





```
Path:      /dao/chain/42161/create/
Browser:   Chrome 107.0.0.0 on Mac OS 10.15.7
Viewport:  1966 x 1177 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-183--sporosdaoapp-dev.netlify.app%2Fdao%2Fchain%2F42161%2Fcreate%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=107.0&resolution=1966x1177&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-183--sporosdaoapp-dev.netlify.app/dao/chain/42161/create/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6398f4f0a229730008a589ea&commentID=639a31fc74ad24405134eb55&resolution=resolved)

**Comment by lipmaneth** [comment]
screenshot

Can't see founder fields. Side bar copy and background is discolored.
<details><summary>Browser metadata</summary>





```
Path:      /dao/chain/42161/create/stepper/
Browser:   Chrome 107.0.0.0 on Mac OS 10.15.7
Viewport:  1966 x 1177 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-183--sporosdaoapp-dev.netlify.app%2Fdao%2Fchain%2F42161%2Fcreate%2Fstepper%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=107.0&resolution=1966x1177&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-183--sporosdaoapp-dev.netlify.app/dao/chain/42161/create/stepper/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6398f4f0a229730008a589ea&commentID=639a32e1ba39bc414a14bfd3&resolution=resolved)

**Comment by lipmaneth** [comment]
screenshot

Can't see settings fields. Side bar with content discolored. 
<details><summary>Browser metadata</summary>





```
Path:      /dao/chain/42161/create/stepper/
Browser:   Chrome 107.0.0.0 on Mac OS 10.15.7
Viewport:  1966 x 1177 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-183--sporosdaoapp-dev.netlify.app%2Fdao%2Fchain%2F42161%2Fcreate%2Fstepper%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=107.0&resolution=1966x1177&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-183--sporosdaoapp-dev.netlify.app/dao/chain/42161/create/stepper/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6398f4f0a229730008a589ea&commentID=639a33718095c53c9774edcf&resolution=resolved)

**Comment by lipmaneth** [comment]
recording

Will we not charge at launch? I see we're waiving the fee. Btw Ignore the ending. I rejected the txn which is why you see the error message.
<details><summary>Browser metadata</summary>





```
Path:      /dao/chain/42161/create/stepper/
Browser:   Chrome 107.0.0.0 on Mac OS 10.15.7
Viewport:  1966 x 1177 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-183--sporosdaoapp-dev.netlify.app%2Fdao%2Fchain%2F42161%2Fcreate%2Fstepper%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=107.0&resolution=1966x1177&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-183--sporosdaoapp-dev.netlify.app/dao/chain/42161/create/stepper/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6398f4f0a229730008a589ea&commentID=639a346f88e78b5057c08bc4&resolution=resolved)

**Comment by lipmaneth** [comment]
recording

clicking the menu options doesn't do anything
<details><summary>Browser metadata</summary>





```
Path:      /dao/chain/42161/create/stepper/
Browser:   Chrome 107.0.0.0 on Mac OS 10.15.7
Viewport:  1966 x 1177 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-183--sporosdaoapp-dev.netlify.app%2Fdao%2Fchain%2F42161%2Fcreate%2Fstepper%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=107.0&resolution=1966x1177&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-183--sporosdaoapp-dev.netlify.app/dao/chain/42161/create/stepper/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6398f4f0a229730008a589ea&commentID=639a34b8ba39bc424714d291&resolution=resolved)

**Comment by lipmaneth** [comment]
recording

I mentioned dark/light mode in a previous comment but how do you switch back and forth between the two? I don't see that option. 
<details><summary>Browser metadata</summary>





```
Path:      /dao/chain/5/create/
Browser:   Chrome 107.0.0.0 on Mac OS 10.15.7
Viewport:  1966 x 1177 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-183--sporosdaoapp-dev.netlify.app%2Fdao%2Fchain%2F5%2Fcreate%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=107.0&resolution=1966x1177&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-183--sporosdaoapp-dev.netlify.app/dao/chain/5/create/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6398f4f0a229730008a589ea&commentID=639a352d74ad24437c34ebd0&resolution=resolved)

**Comment by lipmaneth** [comment]
screenshot

This top bar was confusing. Almost looks like a search bar but when I clicked the X I saw it took me out of this screen back to the homepage.
<details><summary>Browser metadata</summary>





```
Path:      /dao/chain/5/create/
Browser:   Chrome 107.0.0.0 on Mac OS 10.15.7
Viewport:  1966 x 1177 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-183--sporosdaoapp-dev.netlify.app%2Fdao%2Fchain%2F5%2Fcreate%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=107.0&resolution=1966x1177&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-183--sporosdaoapp-dev.netlify.app/dao/chain/5/create/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6398f4f0a229730008a589ea&commentID=639a35bdd4946a50963744e8&resolution=resolved)

**Comment by lipmaneth** [comment]
recording

First screen still has formatting issues on the right side of the page. Also at the top above "Launch Your Company in Minutes"
<details><summary>Browser metadata</summary>





```
Path:      /dao/chain/42161/create/
Browser:   Chrome 108.0.0.0 on Mac OS 10.15.7
Viewport:  1966 x 1177 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-183--sporosdaoapp-dev.netlify.app%2Fdao%2Fchain%2F42161%2Fcreate%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=108.0&resolution=1966x1177&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-183--sporosdaoapp-dev.netlify.app/dao/chain/42161/create/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=639b8ae8d9b4720008a2e0fc&commentID=639bcd8886aa932fb27e6122&resolution=resolved)

**Comment by lipmaneth** [comment]
recording


<details><summary>Browser metadata</summary>





```
Path:      /dao/chain/42161/create/stepper/
Browser:   Chrome 108.0.0.0 on Mac OS 10.15.7
Viewport:  1966 x 1177 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-183--sporosdaoapp-dev.netlify.app%2Fdao%2Fchain%2F42161%2Fcreate%2Fstepper%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=108.0&resolution=1966x1177&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-183--sporosdaoapp-dev.netlify.app/dao/chain/42161/create/stepper/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=639b8ae8d9b4720008a2e0fc&commentID=639bcdb886aa932fb27e6201&resolution=resolved)

**Comment by lipmaneth** [comment]
recording

Nice! The Founder fields are legible now! See formatting issues with the right side and top of the page. Not sure if the menu options should be clickable but they don't appear to be.
<details><summary>Browser metadata</summary>





```
Path:      /dao/chain/42161/create/stepper/
Browser:   Chrome 108.0.0.0 on Mac OS 10.15.7
Viewport:  1966 x 1177 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-183--sporosdaoapp-dev.netlify.app%2Fdao%2Fchain%2F42161%2Fcreate%2Fstepper%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=108.0&resolution=1966x1177&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-183--sporosdaoapp-dev.netlify.app/dao/chain/42161/create/stepper/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=639b8ae8d9b4720008a2e0fc&commentID=639bce026dbf592f5a3edb63&resolution=resolved)

**Comment by lipmaneth** [comment]
recording

Nice! Settings fields are visible and look great. Right side is still not formatted properly. 
<details><summary>Browser metadata</summary>





```
Path:      /dao/chain/42161/create/stepper/
Browser:   Chrome 108.0.0.0 on Mac OS 10.15.7
Viewport:  1966 x 1177 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-183--sporosdaoapp-dev.netlify.app%2Fdao%2Fchain%2F42161%2Fcreate%2Fstepper%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=108.0&resolution=1966x1177&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-183--sporosdaoapp-dev.netlify.app/dao/chain/42161/create/stepper/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=639b8ae8d9b4720008a2e0fc&commentID=639bcf07a264823b63a42dc0&resolution=resolved)

**Comment by lipmaneth** [comment]
recording

Looking good! May consider changing the subheader I've highlighted to a different color bc it's kind of hard to read. Right side of the screen is not formatted properly. 
<details><summary>Browser metadata</summary>





```
Path:      /dao/chain/42161/create/stepper/
Browser:   Chrome 108.0.0.0 on Mac OS 10.15.7
Viewport:  1966 x 1177 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-183--sporosdaoapp-dev.netlify.app%2Fdao%2Fchain%2F42161%2Fcreate%2Fstepper%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=108.0&resolution=1966x1177&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-183--sporosdaoapp-dev.netlify.app/dao/chain/42161/create/stepper/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=639b8ae8d9b4720008a2e0fc&commentID=639bcf735080cd32e34987d8&resolution=resolved)

**Comment by lipmaneth** [comment]
screenshot

Looking good! See right side of the screen again.
<details><summary>Browser metadata</summary>





```
Path:      /dao/chain/42161/create/stepper/
Browser:   Chrome 108.0.0.0 on Mac OS 10.15.7
Viewport:  1966 x 1177 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-183--sporosdaoapp-dev.netlify.app%2Fdao%2Fchain%2F42161%2Fcreate%2Fstepper%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=108.0&resolution=1966x1177&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-183--sporosdaoapp-dev.netlify.app/dao/chain/42161/create/stepper/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=639b8ae8d9b4720008a2e0fc&commentID=639bcfc08eea523b085b75c9&resolution=resolved)

**Comment by EdgeCaser** [comment]
Also getting the invisible fields bug . This is on a WIndows 11 machine using Brave
image

**Comment by ivelin** [comment]
> recording
> 
> Nice! The Founder fields are legible now! See formatting issues with the right side and top of the page. Not sure if the menu options should be clickable but they don't appear to be.
> 
> Browser metadata
> [Open Deploy Preview](https://deploy-preview-183--sporosdaoapp-dev.netlify.app/dao/chain/42161/create/stepper/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=639b8ae8d9b4720008a2e0fc&commentID=639bce026dbf592f5a3edb63&resolution=resolved)

Good feedback.

Navigation tabs are not supposed to be clickable. Just show progress. I did make changes yesterday to make sure the mouse pointer does not indicate clickable items. Also added checkmarks next to tabs that have been completed. If that is still confusing, we can switch to a more standard [MUI stepper](https://mui.com/material-ui/react-stepper/).

**Comment by kleb-33** [comment]
image
Great that the founder fields are legible. In the Email field, Mail Tooltip Icon is showing as text not graphic. And note the right hand panel of the screen which is white with text not visible.

**Comment by kleb-33** [comment]
image

On settings page, field for Voting Period is set to hours. This is not adjustable. If I want to set a voting period to be < 1 hr (e.g 15 mins) the warning message appears telling me 'Voting period has to be a positive number'. 0.25 hrs is a positive number so either:
1. Warning message needs to be adjusted to say that voting period has to be minimum 1 hr
2. We give users the option of setting voting period to less than one hour
3. We give users the option of setting voting period in minutes instead of hours

3 is the best option from user perspective but probably the most work. 1 is the simplest fix in short term.

**Comment by kleb-33** [comment]
image
The Note! section on the right hand panel is not relevant anymore. We had this in the flow when there was no Settings page. As users are inputting their own settings, we can remove this paragraph from the Confirmation page.

**Comment by kleb-33** [comment]
image

Panel on right should read:
' Can I launch my company with more than one founder?
Yes. You can add up to 5 founders when you launch your company.'

**Comment by kleb-33** [comment]
image
Minor point but can we remove the capital letters from the words 'Review All Settings' on right-hand panel. Should read:
'Carefully review all settings!'

**Comment by ivelin** [comment]
> recording
> 
> I mentioned dark/light mode in a previous comment but how do you switch back and forth between the two? I don't see that option.
> 
> Browser metadata
> [Open Deploy Preview](https://deploy-preview-183--sporosdaoapp-dev.netlify.app/dao/chain/5/create/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6398f4f0a229730008a589ea&commentID=639a352d74ad24437c34ebd0&resolution=resolved)

Currently the app picks up dynamically the OS mode. Usually light during daytime and dark at night. We can add an explicit switch if users ask for it.

**Comment by ivelin** [comment]
> image
> 
> On settings page, field for Voting Period is set to hours. This is not adjustable. If I want to set a voting period to be < 1 hr (e.g 15 mins) the warning message appears telling me 'Voting period has to be a positive number'. 0.25 hrs is a positive number so either:
> 
> 1. Warning message needs to be adjusted to say that voting period has to be minimum 1 hr
> 2. We give users the option of setting voting period to less than one hour
> 3. We give users the option of setting voting period in minutes instead of hours
> 
> 3 is the best option from user perspective but probably the most work. 1 is the simplest fix in short term.

OK, will do 1 for now and see how users react.

**Pull request merged**
