### PR TITLE
feat: homepage refactor

### PR DESCRIPTION
**Pull request by ivelin**
[x] app home page refactor to align with Kali's UI behavior
[x] use Kali frontend react libs for consistency
[x] move to rainbowkit + wagmi for web3 context management
[x] use kali subgraph as a datasource vs mongodb to list DAOs that user is in
[x] use react-query + graphql-request for cached graphql data fetch
[x] simplified People page
  - use subgraph instead of mongodb
  - lookup ENS name and avatar for person card
  - show person token stake % in DAO
  - remove invitations and profile edit for MVP

TODO:
[ ] Clean up test suite and add coverage

### CODE REVIEW

**Comment by ivelin** [comment]
Screen Shot 2022-07-01 at 7 57 22 PM

**Comment by ivelin** [comment]
Screen Shot 2022-07-01 at 8 00 13 PM

**Review by opny721 — APPROVED** [review]
Great, lgtm

**Comment by ivelin** [comment]
Screen Shot 2022-07-02 at 2 26 29 AM

**Pull request merged**
