### PR TITLE
added cron service to send notifications

### PR DESCRIPTION
**Pull request by opny721**
- fetch from Kali subgraph
- sync local db
- send a one time notification to a discord channel with the proposal message

### CODE REVIEW

**Comment by ivelin** [comment]
@opny721 looks very cool. Created a discord webhook as described [here](https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks) and shared in our discord dev channel. Please test.

**Comment by ivelin** [comment]
@opny721 question about syncing to local db. Is that necessary given that notifications are already indexed and available as a public subgraph? Maybe we only need to store a local counter for the last event id that users were notified about. That might be enough to prevent duplicate notifications. WDYT?

**Comment by opny721** [comment]
Please keep it open, I would test on the test channel. I will set this to draft later, seems cannot do from mobile

**Comment by ivelin** [comment]
> Please keep it open, I would test on the test channel. I will set this to draft later, seems cannot do from mobile

@opny721  All checks passing now. Would you like me to merge?

**Comment by ivelin** [comment]
@opny721 converted to draft until you green light it.

**Comment by opny721** [comment]
Sorry, I reviewed today and is good to go for me.

**Pull request merged**
