### PR TITLE
feat: UX flows for handling PM proposals (draft)

### PR DESCRIPTION
**Pull request by ivelin**
- [x] Implement voting and processing for PM proposals (subset of #144)
- [x] Cover edge cases:
  - [x] Maximize top app bar when no menu drawer
  - [x] Highlight next pending proposal in queue
  - [x] Do not show Propose button for any proposal that cannot be processed yet
  - [x] Markdown edit and view for PM description field
  - [x] Voting contract write 
  - [x] Prevent duplicate voting error
  - [x] Prevent voting wallet errors (expired proposal, already voted, etc.)
  - [x] Show list of voters table
  - [x] Auto refresh proposal details page (to reflect blockchain updates for voting, expiration, quorum and other status changes)
  - [x] Refresh prop details page after casting a vote (submit vote button)
  - [x] Front end validation whether a proposal is ready to process. Disable when Process will result in blockchain error.
  - [x] Show snackbar with CTA for next pending proposal to process
- [x] 80% test coverage
- [x] User testing
  - [x] Address user issues by @lipmaneth and others reported further below in this thread

Signed-off-by: ivelin <ivelin.eth@gmail.com>

### CODE REVIEW

**Comment by ivelin** [comment]
Quick update. There is a setback due to issues with subgraph. It does not seem to update for a while , which affects poorly UX. Just noticed Kali switched to direct RPC for proposals recently. It's a bummer because subgraph was a big middleware convenience. Not having it requires rewriting front end code to query directly RPC, which takes longer time to write code, test and doesn't scale for many users. In summary, it will take a few more days to rewrite the proposal data access code.

**Comment by ivelin** [comment]
recording


<details><summary>Browser metadata</summary>





```
Path:      /dao/chain/5/address/0xe237747055b12f4da323bc559ac8d5eb66aac2f7/proposals/
Browser:   Chrome 107.0.0.0 on Mac OS 10.15.7
Viewport:  2731 x 1336 @1x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-174--sporosdaoapp-dev.netlify.app%2Fdao%2Fchain%2F5%2Faddress%2F0xe237747055b12f4da323bc559ac8d5eb66aac2f7%2Fproposals%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=107.0&resolution=2731x1336&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-174--sporosdaoapp-dev.netlify.app/dao/chain/5/address/0xe237747055b12f4da323bc559ac8d5eb66aac2f7/proposals/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=63642069aea7b500084e57d3&commentID=63651649f1f3d2007fef78b3&resolution=resolved)

**Comment by lipmaneth** [comment]
A new user left a comment. This user must be approved by a Netlify team owner before comments can be displayed.

[Approve this user](https://app.netlify.com/teams/sponsored-oss-account-qztqiak/reviewers)

**Comment by lipmaneth** [comment]
Clicking on some of the proposals seems to crash the app. For example, #121.
<details><summary>Browser metadata</summary>





```
Path:      /dao/chain/42161/address/0x28feac06dc72188b385478b507f7c7a39a7026d5/proposals/121
Browser:   Chrome 106.0.0.0 on Mac OS 10.15.7
Viewport:  1635 x 1177 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-174--sporosdaoapp-dev.netlify.app%2Fdao%2Fchain%2F42161%2Faddress%2F0x28feac06dc72188b385478b507f7c7a39a7026d5%2Fproposals%2F121&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=106.0&resolution=1635x1177&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-174--sporosdaoapp-dev.netlify.app/dao/chain/42161/address/0x28feac06dc72188b385478b507f7c7a39a7026d5/proposals/121) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=63698f7dac4e330008655052&commentID=636a66a8a6cf8f2a13441f89&resolution=resolved)

**Comment by lipmaneth** [comment]
screenshot


<details><summary>Browser metadata</summary>





```
Path:      /dao/chain/42161/address/0x28feac06dc72188b385478b507f7c7a39a7026d5/proposals/
Browser:   Chrome 106.0.0.0 on Mac OS 10.15.7
Viewport:  1635 x 1177 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-174--sporosdaoapp-dev.netlify.app%2Fdao%2Fchain%2F42161%2Faddress%2F0x28feac06dc72188b385478b507f7c7a39a7026d5%2Fproposals%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=106.0&resolution=1635x1177&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-174--sporosdaoapp-dev.netlify.app/dao/chain/42161/address/0x28feac06dc72188b385478b507f7c7a39a7026d5/proposals/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=63698f7dac4e330008655052&commentID=636a674eaa94121f1cffaab6&resolution=resolved)

**Comment by lipmaneth** [comment]
screenshot

Can't click 'details' button for non-PM proposals. 


<details><summary>Browser metadata</summary>





```
Path:      /dao/chain/42161/address/0x28feac06dc72188b385478b507f7c7a39a7026d5/proposals/
Browser:   Chrome 106.0.0.0 on Mac OS 10.15.7
Viewport:  1803 x 1177 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-174--sporosdaoapp-dev.netlify.app%2Fdao%2Fchain%2F42161%2Faddress%2F0x28feac06dc72188b385478b507f7c7a39a7026d5%2Fproposals%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=106.0&resolution=1803x1177&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-174--sporosdaoapp-dev.netlify.app/dao/chain/42161/address/0x28feac06dc72188b385478b507f7c7a39a7026d5/proposals/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=636f09797b10f6000879b406&commentID=63724e5147347a009a77fdf2&resolution=resolved)

**Comment by lipmaneth** [comment]
screenshot

How should we handle notifications such as these where very old proposals (in this case from June) haven't been processed? Perhaps at least let the user delete this notification so it doesn't continuously show up?


<details><summary>Browser metadata</summary>





```
Path:      /dao/chain/42161/address/0x28feac06dc72188b385478b507f7c7a39a7026d5/proposals/
Browser:   Chrome 106.0.0.0 on Mac OS 10.15.7
Viewport:  1803 x 1177 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-174--sporosdaoapp-dev.netlify.app%2Fdao%2Fchain%2F42161%2Faddress%2F0x28feac06dc72188b385478b507f7c7a39a7026d5%2Fproposals%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=106.0&resolution=1803x1177&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-174--sporosdaoapp-dev.netlify.app/dao/chain/42161/address/0x28feac06dc72188b385478b507f7c7a39a7026d5/proposals/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=636f09797b10f6000879b406&commentID=63724f5e4b2485004e321105&resolution=resolved)

**Comment by briareus-the-titan** [comment]
If you connect your wallet and are on a different network than Arbitrum, you need to manually refresh

**Comment by ivelin** [comment]
> If you connect your wallet and are on a different network than Arbitrum, you need to manually refresh

Good catch. Sounds like a wallet callback handling that applies across the app. Should we open this as a separate bug report and handle outside this PR to reduce bloat.

**Comment by ivelin** [comment]
> https://deploy-preview-174--sporosdaoapp-dev.netlify.app/

OK, for the time being, there will be no Details button shown at all for proposals other than PM. See screenshot.

Each proposal type requires thoughtful UX to represent the underlying intention to users in a meaningful way.

Since this PR is already quite bloated as is with 31 file changes, we will be adding UX flows for other proposal types in separate PRs. Next on the TODO list are MINT, ESCAPE, QUORUM, MAJORITY, VOTING_PERIOD. If you prefer, these can be tracked as separate Feature Requests on the product board. @EdgeCaser what would you recommend?
Screen Shot 2022-11-16 at 10 52 48 AM

**Comment by ivelin** [comment]
> screenshot
> 
> How should we handle notifications such as these where very old proposals (in this case from June) haven't been processed? Perhaps at least let the user delete this notification so it doesn't continuously show up?
> 
> Browser metadata
> [Open Deploy Preview](https://deploy-preview-174--sporosdaoapp-dev.netlify.app/dao/chain/42161/address/0x28feac06dc72188b385478b507f7c7a39a7026d5/proposals/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=636f09797b10f6000879b406&commentID=63724f5e4b2485004e321105&resolution=resolved)

Interesting issue. Needs some thought. Working on it.

**Comment by ivelin** [comment]
> > screenshot
> > How should we handle notifications such as these where very old proposals (in this case from June) haven't been processed? Perhaps at least let the user delete this notification so it doesn't continuously show up?
> > Browser metadata
> > [Open Deploy Preview](https://deploy-preview-174--sporosdaoapp-dev.netlify.app/dao/chain/42161/address/0x28feac06dc72188b385478b507f7c7a39a7026d5/proposals/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=636f09797b10f6000879b406&commentID=63724f5e4b2485004e321105&resolution=resolved)
> 
> Interesting issue. Needs some thought. Working on it.

Found the root cause of this issue. Will need some support from Kali. Looks like a subgraph bug:
https://discord.com/channels/923399898769018921/925091695677309059/1042502724790522006

https://arbiscan.io/address/0x28fea
Screen Shot 2022-11-16 at 12 16 32 PM

Screen Shot 2022-11-16 at 12 15 36 PM
c06dc72188b385478b507f7c7a39a7026d5#readContract

Screen Shot 2022-11-16 at 12 15 26 PM

Screen Shot 2022-11-16 at 12 12 32 PM

**Comment by ivelin** [comment]
> > > screenshot
> > > How should we handle notifications such as these where very old proposals (in this case from June) haven't been processed? Perhaps at least let the user delete this notification so it doesn't continuously show up?
> > > Browser metadata
> > > [Open Deploy Preview](https://deploy-preview-174--sporosdaoapp-dev.netlify.app/dao/chain/42161/address/0x28feac06dc72188b385478b507f7c7a39a7026d5/proposals/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=636f09797b10f6000879b406&commentID=63724f5e4b2485004e321105&resolution=resolved)
> > 
> > 
> > Interesting issue. Needs some thought. Working on it.
> 
> Found the root cause of this issue. Will need some support from Kali. Looks like a subgraph bug: https://discord.com/channels/923399898769018921/925091695677309059/1042502724790522006
> 
> https://arbiscan.io/address/0x28fea Screen Shot 2022-11-16 at 12 16 32 PM
> 
> Screen Shot 2022-11-16 at 12 15 36 PM c06dc72188b385478b507f7c7a39a7026d5#readContract
> 
> Screen Shot 2022-11-16 at 12 15 26 PM
> 
> Screen Shot 2022-11-16 at 12 12 32 PM

Path to solution confirmed with @nerderlyne . Starting work on PR:
https://github.com/kalidao/kali-subgraph/pull/18

**Comment by lipmaneth** [comment]
recording

As a user, there isn't an easy way to get to the previous screen. The 'back arrow' button hides the side bar, but does not take me to the previous screen. To get to a previous screen, I need to hit 'back' in my browser tab.
<details><summary>Browser metadata</summary>





```
Path:      /dao/chain/42161/address/0x28feac06dc72188b385478b507f7c7a39a7026d5/projects/
Browser:   Chrome 107.0.0.0 on Mac OS 10.15.7
Viewport:  2094 x 1177 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-174--sporosdaoapp-dev.netlify.app%2Fdao%2Fchain%2F42161%2Faddress%2F0x28feac06dc72188b385478b507f7c7a39a7026d5%2Fprojects%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=107.0&resolution=2094x1177&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-174--sporosdaoapp-dev.netlify.app/dao/chain/42161/address/0x28feac06dc72188b385478b507f7c7a39a7026d5/projects/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=637eb9802307580008c112ea&commentID=63810187218017480311a9de&resolution=resolved)

**Comment by lipmaneth** [comment]
recording

Clicking on the project details buttons from the proposals main page takes me to a new screen with an error message saying the proposal format isn't supported and I need to visit Kali. That doesn't seem right. We should be able to show details on that screen? 
<details><summary>Browser metadata</summary>





```
Path:      /dao/chain/42161/address/0x28feac06dc72188b385478b507f7c7a39a7026d5/proposals/
Browser:   Chrome 107.0.0.0 on Mac OS 10.15.7
Viewport:  2094 x 1177 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-174--sporosdaoapp-dev.netlify.app%2Fdao%2Fchain%2F42161%2Faddress%2F0x28feac06dc72188b385478b507f7c7a39a7026d5%2Fproposals%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=107.0&resolution=2094x1177&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-174--sporosdaoapp-dev.netlify.app/dao/chain/42161/address/0x28feac06dc72188b385478b507f7c7a39a7026d5/proposals/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=637eb9802307580008c112ea&commentID=63810262573709533d176b17&resolution=resolved)

**Comment by lipmaneth** [comment]
screenshot

The 'info' icon is a bit confusing. I was expecting to hover over it and be shown a tool tip or some more info. Could just be me though.
<details><summary>Browser metadata</summary>





```
Path:      /dao/chain/42161/address/0x28feac06dc72188b385478b507f7c7a39a7026d5/projects/114/tribute
Browser:   Chrome 107.0.0.0 on Mac OS 10.15.7
Viewport:  2094 x 1177 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-174--sporosdaoapp-dev.netlify.app%2Fdao%2Fchain%2F42161%2Faddress%2F0x28feac06dc72188b385478b507f7c7a39a7026d5%2Fprojects%2F114%2Ftribute&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=107.0&resolution=2094x1177&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-174--sporosdaoapp-dev.netlify.app/dao/chain/42161/address/0x28feac06dc72188b385478b507f7c7a39a7026d5/projects/114/tribute) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=637eb9802307580008c112ea&commentID=6381037eadf1a0593c9111a4&resolution=resolved)

**Comment by lipmaneth** [comment]
screenshot

It's my understanding that implementing voting for PM proposals is inside the scope of this PR. If so, is there a need to give users the option to visit Kali for PM proposals? What info/actions could they get at Kali that they couldn't get inside our app?
<details><summary>Browser metadata</summary>





```
Path:      /dao/chain/42161/address/0x28feac06dc72188b385478b507f7c7a39a7026d5/proposals/
Browser:   Chrome 107.0.0.0 on Mac OS 10.15.7
Viewport:  2094 x 1177 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-174--sporosdaoapp-dev.netlify.app%2Fdao%2Fchain%2F42161%2Faddress%2F0x28feac06dc72188b385478b507f7c7a39a7026d5%2Fproposals%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=107.0&resolution=2094x1177&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-174--sporosdaoapp-dev.netlify.app/dao/chain/42161/address/0x28feac06dc72188b385478b507f7c7a39a7026d5/proposals/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=637eb9802307580008c112ea&commentID=6381057cacf33a5b95a9c8bb&resolution=resolved)

**Comment by lipmaneth** [comment]
recording

The font size and formatting of the cards for the projects page and proposals page is different. 
<details><summary>Browser metadata</summary>





```
Path:      /dao/chain/42161/address/0x28feac06dc72188b385478b507f7c7a39a7026d5/proposals/
Browser:   Chrome 107.0.0.0 on Mac OS 10.15.7
Viewport:  2094 x 1177 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-174--sporosdaoapp-dev.netlify.app%2Fdao%2Fchain%2F42161%2Faddress%2F0x28feac06dc72188b385478b507f7c7a39a7026d5%2Fproposals%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=107.0&resolution=2094x1177&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-174--sporosdaoapp-dev.netlify.app/dao/chain/42161/address/0x28feac06dc72188b385478b507f7c7a39a7026d5/proposals/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=637eb9802307580008c112ea&commentID=6381061bacf33a5ce9a9c823&resolution=resolved)

**Comment by lipmaneth** [comment]
recording

Clicking the details button sends me to a screen saying more info can't be given. If that's true, then we should at least provide a link to Kali's app from that 2nd page.
<details><summary>Browser metadata</summary>





```
Path:      /dao/chain/42161/address/0x28feac06dc72188b385478b507f7c7a39a7026d5/proposals/40
Browser:   Chrome 107.0.0.0 on Mac OS 10.15.7
Viewport:  2094 x 1177 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-174--sporosdaoapp-dev.netlify.app%2Fdao%2Fchain%2F42161%2Faddress%2F0x28feac06dc72188b385478b507f7c7a39a7026d5%2Fproposals%2F40&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=107.0&resolution=2094x1177&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-174--sporosdaoapp-dev.netlify.app/dao/chain/42161/address/0x28feac06dc72188b385478b507f7c7a39a7026d5/proposals/40) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=637eb9802307580008c112ea&commentID=63810679d901c5549e138d29&resolution=resolved)

**Comment by lipmaneth** [comment]
screenshot

Clicking the Kali button sends a user to the main proposal screen inside the Kali app. I'm unclear if there's really a reason to send users to Kali, but if so, a better experience would be to send them directly to the relevant proposal. For example, if I click 'Kali' on the Proposal #114 of the sporos app, then it would take me to the #114 in the Kali app, not the top level proposal page in the kali app. 
<details><summary>Browser metadata</summary>





```
Path:      /dao/chain/42161/address/0x28feac06dc72188b385478b507f7c7a39a7026d5/projects/
Browser:   Chrome 107.0.0.0 on Mac OS 10.15.7
Viewport:  2094 x 1177 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-174--sporosdaoapp-dev.netlify.app%2Fdao%2Fchain%2F42161%2Faddress%2F0x28feac06dc72188b385478b507f7c7a39a7026d5%2Fprojects%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=107.0&resolution=2094x1177&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-174--sporosdaoapp-dev.netlify.app/dao/chain/42161/address/0x28feac06dc72188b385478b507f7c7a39a7026d5/projects/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=637eb9802307580008c112ea&commentID=63810786a69c555f7965653e&resolution=resolved)

**Comment by ivelin** [comment]
Incorrect error "Proposal type not Supported" when PM proposal is CLOSED for voting.

recording


<details><summary>Browser metadata</summary>





```
Path:      /dao/chain/42161/address/0x28feac06dc72188b385478b507f7c7a39a7026d5/proposals/97
Browser:   Chrome 107.0.0.0 on Mac OS 10.15.7
Viewport:  2466 x 1279 @1x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-174--sporosdaoapp-dev.netlify.app%2Fdao%2Fchain%2F42161%2Faddress%2F0x28feac06dc72188b385478b507f7c7a39a7026d5%2Fproposals%2F97&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=107.0&resolution=2466x1279&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-174--sporosdaoapp-dev.netlify.app/dao/chain/42161/address/0x28feac06dc72188b385478b507f7c7a39a7026d5/proposals/97) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=637eb9802307580008c112ea&commentID=6384dfc8cb2392173ef8ac56&resolution=resolved)

**Comment by ivelin** [comment]
UPDATE:
Fixed here: https://github.com/SporosDAO/sweat-token/pull/181

> Incorrect error "Proposal type not Supported" when proposal is a PM extension.
> 
> recording
> 
> Browser metadata
> [Open Deploy Preview](https://deploy-preview-174--sporosdaoapp-dev.netlify.app/dao/chain/42161/address/0x28feac06dc72188b385478b507f7c7a39a7026d5/proposals/97) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=637eb9802307580008c112ea&commentID=6384dfc8cb2392173ef8ac56&resolution=resolved)

**Comment by ivelin** [comment]
Kali Subgraph and Sporos frontened fixes for this issue are now patched. PRs pending peer review:
https://github.com/SporosDAO/sweat-token/pull/182

cc: @lipmaneth 

> > > screenshot
> > > How should we handle notifications such as these where very old proposals (in this case from June) haven't been processed? Perhaps at least let the user delete this notification so it doesn't continuously show up?
> > > Browser metadata
> > > [Open Deploy Preview](https://deploy-preview-174--sporosdaoapp-dev.netlify.app/dao/chain/42161/address/0x28feac06dc72188b385478b507f7c7a39a7026d5/proposals/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=636f09797b10f6000879b406&commentID=63724f5e4b2485004e321105&resolution=resolved)
> > 
> > 
> > Interesting issue. Needs some thought. Working on it.
> 
> Found the root cause of this issue. Will need some support from Kali. Looks like a subgraph bug: https://discord.com/channels/923399898769018921/925091695677309059/1042502724790522006
> 
> https://arbiscan.io/address/0x28fea Screen Shot 2022-11-16 at 12 16 32 PM
> 
> Screen Shot 2022-11-16 at 12 15 36 PM c06dc72188b385478b507f7c7a39a7026d5#readContract
> 
> Screen Shot 2022-11-16 at 12 15 26 PM
> 
> Screen Shot 2022-11-16 at 12 12 32 PM

**Comment by ivelin** [comment]
> recording
> 
> The font size and formatting of the cards for the projects page and proposals page is different.
> 
> Browser metadata
> [Open Deploy Preview](https://deploy-preview-174--sporosdaoapp-dev.netlify.app/dao/chain/42161/address/0x28feac06dc72188b385478b507f7c7a39a7026d5/proposals/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=637eb9802307580008c112ea&commentID=6381061bacf33a5ce9a9c823&resolution=resolved)

Right. In the case of projects the Title is just the Project title. In the case of proposal, there is no title field. Only description. So we do a bit of a hack by merging PM title and settings into proposal description field, which becomes more verbose. Hence the smaller font to display. Since we know which proposals are of type PM, we can display just the PM title instead of the Kali proposal description field. Would that be a better UX?

**Comment by ivelin** [comment]
Valid point. The thinking was to allow users to have a fallback front end. We can hide the Kali button for PM cards or replace with Etherscan/Arbiscan or leave as is. Let's branch this comment as a separate Good First Issue and agree on desired UX. It's a small self contained fix.

> screenshot
> 
> Clicking the Kali button sends a user to the main proposal screen inside the Kali app. I'm unclear if there's really a reason to send users to Kali, but if so, a better experience would be to send them directly to the relevant proposal. For example, if I click 'Kali' on the Proposal #114 of the sporos app, then it would take me to the #114 in the Kali app, not the top level proposal page in the kali app.
> 
> Browser metadata
> [Open Deploy Preview](https://deploy-preview-174--sporosdaoapp-dev.netlify.app/dao/chain/42161/address/0x28feac06dc72188b385478b507f7c7a39a7026d5/projects/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=637eb9802307580008c112ea&commentID=63810786a69c555f7965653e&resolution=resolved)

**Comment by ivelin** [comment]
Interesting. This is a default MUI component decoration for informative alerts. 
Let's branch this as a separate Good First Issue and agree on desired UX. It's a small self contained fix.

> screenshot
> 
> The 'info' icon is a bit confusing. I was expecting to hover over it and be shown a tool tip or some more info. Could just be me though.
> 
> Browser metadata
> [Open Deploy Preview](https://deploy-preview-174--sporosdaoapp-dev.netlify.app/dao/chain/42161/address/0x28feac06dc72188b385478b507f7c7a39a7026d5/projects/114/tribute) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=637eb9802307580008c112ea&commentID=6381037eadf1a0593c9111a4&resolution=resolved)

**Pull request merged**
